#==========================================================
#= GestUser Web Service - Versione Base
#==========================================================

server:
  port: 8100
spring:
  application:
    name: GestUser
#==========================================================
#= PARAMETRI DB MONGODB 
#==========================================================
  data:
    mongodb:
      host: 72.23.0.3     # Usa il nome del servizio Docker invece dell'IP
      port: 27017         # Questa linea Ã¨ opzionale se usi la porta di default
      database: ms-users
      authentication-database: admin
      username: admin
      password: 123_Stella